### PRE and POST ###
-
  name: "StaticPreLightShowStack"
  groups: ["PRE"]
  light_shows:
    - "SensorProcessor"
    - "LightProcessor"
-
  name: "StaticPostLightShowStack"
  groups: ["POST"]
  light_shows:
    - "SensorProcessor"
    - "LightProcessor"

### SENSOR ###

-
  name: "SensorProcessorStack"
  groups: ["SENSOR"]
  light_shows:
    - "SensorProcessor"

### LIGHT ###

-
  name: "LightProcessorStack"
  groups: ["LIGHT"]
  light_shows:
    - "LightProcessor"

### COLOR ###

-
  name: "ColorProcessorStack"
  groups: ["COLOR"]
  light_shows:
    - "ColorProcessor"

### SENSOR and LIGHT ###

-
  name: "OpenLoopLightStack"
  groups: ["OPEN_LOOP"]
  light_shows:
    - "OpenLoopLightGenerator"
-
  name: "LightShowCreatorStack"
  groups: ["OPEN_LOOP"]
  light_shows:
    - "LightShowCreator"
    
-
  name: "LightShowRecorderStack"
  groups: ["OPEN_LOOP"]
  light_shows:
    - "LightShowCreator"
    - "LightShowRecorder"
-
  name: "LightShowPlayerStack"
  groups: ["OPEN_LOOP"]
  light_shows:
    - "LightShowPlayer"
        