### PRE and POST ###
#-
#  name: "StaticPreLightShowStack"
#  groups: ["PRE"]
#  light_shows:
#    - "SensorProcessor"
#-
#  name: "StaticPostLightShowStack"
#  groups: ["POST"]
#  light_shows:
#    - "SensorProcessor"

### SENSORS ###
-
  name: "SensorLinearRiseProcessorStack"
  groups: ["SENSOR_RISE"]
  light_shows:
    - "SensorLinearRiseProcessor"
-
  name: "SensorLinearDecayProcessorStack"
  groups: ["SENSOR_DECAY"]
  light_shows:
    - "SensorLinearDecayProcessor"
-
  name: "SensorButterworthProcessorStack"
  groups: ["SENSOR_DECAY", "SENSOR_RISE"]
  light_shows:
    - "SensorButterworthProcessor"

### LIGHT ###
-
  name: "LightInsideOutProcessorStack"
  groups: ["LIGHT"]
  light_shows:
    - "LightInsideOutProcessor"
-
  name: "LightOutsideInProcessorStack"
  groups: ["LIGHT"]
  light_shows:
    - "LightOutsideInProcessor"

### COLOR ###
-
  name: "ColorProcessorStack"
  groups: ["COLOR"]
  light_shows:
    - "ColorProcessor"
-  
  name: "ColorBlackWhiteProcessorStack"
  groups: ["COLOR"]
  light_shows:
    - "ColorBlackWhiteProcessor"
-  
  name: "ColorBackgroundForegroundProcessorStack"
  groups: ["COLOR"]
  light_shows:
    - "ColorBackgroundForegroundProcessor"

### OPEN_LOOP
-
  name: "OpenLoopLightStack"
  groups: ["OPEN_LOOP"]
  light_shows:
    - "OpenLoopLightGenerator"
-
  name: "LightShowBallCreatorStack"
  groups: ["OPEN_LOOP"]
  light_shows:
    - "LightShowBallCreator"
-
  name: "LightShowPlane0CreatorStack"
  groups: ["OPEN_LOOP"]
  light_shows:
    - "LightShowPlane0Creator"
-
  name: "LightShowPlane1CreatorStack"
  groups: ["OPEN_LOOP"]
  light_shows:
    - "LightShowPlane1Creator"
-
  name: "LightShowPlane2CreatorStack"
  groups: ["OPEN_LOOP"]
  light_shows:
    - "LightShowPlane2Creator"
-
  name: "LightShowPlane3CreatorStack"
  groups: ["OPEN_LOOP"]
  light_shows:
    - "LightShowPlane3Creator"
-
  name: "LightShowIdleOpenLoopStack"
  groups: ["OPEN_LOOP"]
  light_shows:
    - "Idle"

    
### TEST
-
  name: "TestLightGeneratorStack"
  groups: ["OPEN_LOOP", "LIGHT"]
  light_shows:
    - "TestLightGenerator"

### IO
### -> RECORDER    
-
  name: "LightShowRecorder1Stack"
  groups: ["IO"]
  light_shows:
    - "LightShowRecorder1"
-
  name: "LightShowRecorder2Stack"
  groups: ["IO"]
  light_shows:
    - "LightShowRecorder2"
-
  name: "LightShowRecorder3Stack"
  groups: ["IO"]
  light_shows:
    - "LightShowRecorder3"
### -> PLAYER
-
  name: "LightShowPlayer1Stack"
  groups: ["IO"]
  light_shows:
    - "LightShowPlayer1"
-
  name: "LightShowPlayer2Stack"
  groups: ["IO"]
  light_shows:
    - "LightShowPlayer2"
-
  name: "LightShowPlayer3Stack"
  groups: ["IO"]
  light_shows:
    - "LightShowPlayer3"
-
  name: "LightShowIdleIOStack"
  groups: ["IO"]
  light_shows:
    - "Idle"

### BRIGHTNESS
-
  name: "BrightnessProcessorStack"
  groups: ["AUDIO", "BRIGHTNESS"]
  light_shows:
    - "BrightnessProcessor"
    
### AUDIO
-
  name: "AudioProcessorStack"
  groups: ["AUDIO", "BRIGHTNESS"]
  light_shows:
    - "AudioProcessor"
-
  name: "AudioIdleStack"
  groups: ["AUDIO"]
  light_shows:
    - "Idle"
    