### PRE and POST ###
#-
#  name: "StaticPreLightShowStack"
#  groups: ["PRE"]
#  light_shows:
#    - "SensorProcessor"
#-
#  name: "StaticPostLightShowStack"
#  groups: ["POST"]
#  light_shows:
#    - "SensorProcessor"

### SENSORS ###
-
  name: "SensorLinearRiseStack"
  groups: ["SENSOR_RISE"]
  light_shows:
    - "SensorLinearRise"
-
  name: "SensorLinearDecayStack"
  groups: ["SENSOR_DECAY"]
  light_shows:
    - "SensorLinearDecay"
-
  name: "SensorWindowingStack"
  groups: ["SENSOR_RISE"]
  light_shows:
    - "SensorWindowing"
#-
#  name: "SensorButterworthStack"
#  groups: ["SENSOR_DECAY", "SENSOR_RISE"]
#  light_shows:
#    - "SensorButterworth"

### LIGHT ###
-
  name: "LightSwitchStack"
  groups: ["LIGHT"]
  light_shows:
    - "LightSwitch"
-
  name: "LightInsideOutStack"
  groups: ["LIGHT"]
  light_shows:
    - "LightInsideOut"
-
  name: "LightOutsideInStack"
  groups: ["LIGHT"]
  light_shows:
    - "LightOutsideIn"

### COLOR ###
-
  name: "ColorProcessorStack"
  groups: ["COLOR"]
  light_shows:
    - "ColorProcessor"
-  
  name: "ColorBlackWhiteProcessorStack"
  groups: ["COLOR"]
  light_shows:
    - "ColorBlackWhiteProcessor"
-  
  name: "ColorBackgroundForegroundProcessorStack"
  groups: ["COLOR"]
  light_shows:
    - "ColorBackgroundForegroundProcessor"

### OPEN_LOOP
#-
#  name: "OpenLoopLightStack"
#  groups: ["OPEN_LOOP"]
#  light_shows:
#    - "OpenLoopLightGenerator"
#-
#  name: "OpenLoopBallRandomStack"
#  groups: ["OPEN_LOOP"]
#  light_shows:
#    - "OpenLoopBallRandom"
#-
#  name: "OpenLoopBallExpandStack"
#  groups: ["OPEN_LOOP"]
#  light_shows:
#    - "OpenLoopBallExpand"
#-
#  name: "OpenLoopPlane0Stack"
#  groups: ["OPEN_LOOP"]
#  light_shows:
#    - "OpenLoopPlane0"
#-
#  name: "OpenLoopPlane1Stack"
#  groups: ["OPEN_LOOP"]
#  light_shows:
#    - "OpenLoopPlane1"
#-
#  name: "OpenLoopPlane2Stack"
#  groups: ["OPEN_LOOP"]
#  light_shows:
#    - "OpenLoopPlane2"
#-
#  name: "OpenLoopPlane3Stack"
#  groups: ["OPEN_LOOP"]
#  light_shows:
#    - "OpenLoopPlane3"
#-
#  name: "OpenLoopIdleOpenLoopStack"
#  groups: ["OPEN_LOOP"]
#  light_shows:
#    - "Idle"

### TEST
-
  name: "TestLightGeneratorStack"
  groups: ["OPEN_LOOP", "LIGHT"]
  light_shows:
    - "TestLightGenerator"

### IO
### -> RECORDER    
#-
#  name: "IORecorder1Stack"
#  groups: ["IO"]
#  light_shows:
#    - "IORecorder1"
#-
#  name: "IORecorder2Stack"
#  groups: ["IO"]
#  light_shows:
#    - "IORecorder2"
#-
#  name: "IORecorder3Stack"
#  groups: ["IO"]
#  light_shows:
#    - "IORecorder3"
#### -> PLAYER
#-
#  name: "IOPlayer1Stack"
#  groups: ["IO"]
#  light_shows:
#    - "IOPlayer1"
#-
#  name: "IOPlayer2Stack"
#  groups: ["IO"]
#  light_shows:
#    - "IOPlayer2"
#-
#  name: "IOPlayer3Stack"
#  groups: ["IO"]
#  light_shows:
#    - "IOPlayer3"
#-
#  name: "IOIdleIOStack"
#  groups: ["IO"]
#  light_shows:
#    - "Idle"

### BRIGHTNESS
-
  name: "BrightnessProcessorStack"
  groups: ["BRIGHTNESS"]
  light_shows:
    - "BrightnessProcessor"
#-
#  name: "BrightnessAudioProcessorStack"
#  groups: ["BRIGHTNESS"]
#  light_shows:
#    - "BrightnessAudioProcessor"
