### PRE and POST ###
-
  name: "StaticPreLightShowStack"
  groups: ["PRE"]
  light_shows:
    - "SensorProcessor"
    - "LightProcessor"
-
  name: "StaticPostLightShowStack"
  groups: ["POST"]
  light_shows:
    - "SensorProcessor"
    - "LightProcessor"

### SENSOR ###
-
  name: "SensorProcessorStack"
  groups: ["SENSOR"]
  light_shows:
    - "SensorProcessor"

### LIGHT ###
-
  name: "LightProcessorStack"
  groups: ["LIGHT"]
  light_shows:
    - "LightProcessor"

### COLOR ###
-
  name: "ColorProcessorStack"
  groups: ["COLOR"]
  light_shows:
    - "ColorProcessor"
-  
  name: "ColorBlackWhiteProcessorStack"
  groups: ["COLOR"]
  light_shows:
    - "ColorBlackWhiteProcessor"
-  
  name: "ColorBackgroundForegroundProcessorStack"
  groups: ["COLOR"]
  light_shows:
    - "ColorBackgroundForegroundProcessor"

### OPEN_LOOP
-
  name: "OpenLoopLightStack"
  groups: ["OPEN_LOOP"]
  light_shows:
    - "OpenLoopLightGenerator"
-
  name: "LightShowBallCreatorStack"
  groups: ["OPEN_LOOP"]
  light_shows:
    - "LightShowBallCreator"
-
  name: "LightShowPlane0CreatorStack"
  groups: ["OPEN_LOOP"]
  light_shows:
    - "LightShowPlane0Creator"
-
  name: "LightShowPlane1CreatorStack"
  groups: ["OPEN_LOOP"]
  light_shows:
    - "LightShowPlane1Creator"
-
  name: "LightShowPlane2CreatorStack"
  groups: ["OPEN_LOOP"]
  light_shows:
    - "LightShowPlane2Creator"

### IO
### -> RECORDER    
-
  name: "LightShowRecorder1Stack"
  groups: ["IO"]
  light_shows:
    - "LightShowRecorder1"
-
  name: "LightShowRecorder2Stack"
  groups: ["IO"]
  light_shows:
    - "LightShowRecorder2"
-
  name: "LightShowRecorder3Stack"
  groups: ["IO"]
  light_shows:
    - "LightShowRecorder3"
### -> PLAYER
-
  name: "LightShowPlayer1Stack"
  groups: ["IO"]
  light_shows:
    - "LightShowPlayer1"
-
  name: "LightShowPlayer2Stack"
  groups: ["IO"]
  light_shows:
    - "LightShowPlayer2"
-
  name: "LightShowPlayer3Stack"
  groups: ["IO"]
  light_shows:
    - "LightShowPlayer3"

### IDLE
-
  name: "IdleOpenLoopStack"
  groups: ["OPEN_LOOP"]
  light_shows:
    - "Idle"
-
  name: "IdleIOStack"
  groups: ["IO"]
  light_shows:
    - "Idle"
