# This is the index into node_positions set
# to determine the node which sets the zero coordinate of the structure
# setting this to -1 uses the average in x and y
offset_node_indices: [-1]

# List of all nodes in the structure
# Values correspond to x,y,z in meters

# EDIT THIS !!!

node_positions:

  - position: [812.0,   38.0,   3000.0]
  - position: [444.0,   228.0,   3000.0]
  - position: [927.0,   419.0,   3000.0]
  - position: [1168.0,  120.0,   3000.0]
  - position: [1295.0,  508.0,   3000.0]
  - position: [571.0,   660.0,   3000.0]
  - position: [1536.0,  762.0,   3000.0]
  - position: [1409.0,  1105.0,  3000.0]
  - position: [1054.0,  850.0,   3000.0]
  - position: [444.0,   965.0,   3000.0]

  - position: [203.0,   1066.0,  3000.0]
  - position: [330.0,   1409.0,  3000.0]
  - position: [203.0,   1803.0,  3000.0]
  - position: [330.0,   2108.0,  3000.0]
  - position: [571.0,   2463.0,  3000.0]
  - position: [685.0,   1981.0,  3000.0]
  - position: [571.0,   1587.0,  3000.0]
  - position: [685.0,   1066.0,  3000.0]
  - position: [927.0,   1676.0,  3000.0]
  - position: [1054.0,  1295.0,  3000.0]

  - position: [203.0,   2603.0,  3000.0]
  - position: [330.0,   2908.0,  3000.0]
  - position: [330.0,   3264.0,  3000.0]
  - position: [203.0,   3568.0,  3000.0]
  - position: [685.0,   3365.0,  3000.0]
  - position: [685.0,   3086.0,  3000.0]
  - position: [812.0,   2717.0,  3000.0]
  - position: [1168.0,  2616.0,  3000.0]
  - position: [1054.0,  3086.0,  3000.0]
  - position: [1168.0,  3454.0,  3000.0]

  - position: [1676.0,  1346.0,  3000.0]
  - position: [1409.0,  1549.0,  3000.0]
  - position: [1536.0,  1879.0,  3000.0]
  - position: [1168.0,  1968.0,  3000.0]
  - position: [927.0,   2273.0,  3000.0]
  - position: [1295.0,  2298.0,  3000.0]
  - position: [1676.0,  2324.0,  3000.0]
  - position: [1536.0,  2755.0,  3000.0]
  - position: [1409.0,  3124.0,  3000.0]
  - position: [1536.0,  3619.0,  3000.0]


# List of all beams in the structure
# List correspond to pairs of indices of nodes
# nodes: [0, 1] constructs a beam from node 0 to node 1
beams:
  - nodes: [0,1]

sensors:
  -
    nodes: [[0, 0]]
    teensy: 1
  -
    nodes: [[1, 1]]
    teensy: 1
  -
    nodes: [[2, 2]]
    teensy: 1
  -
    nodes: [[3, 3]]
    teensy: 1
  -
    nodes: [[4, 4]]
    teensy: 1
  -
    nodes: [[5, 5]]
    teensy: 1
  -
    nodes: [[6, 6]]
    teensy: 1
  -
    nodes: [[7, 7]]
    teensy: 1
  -
    nodes: [[8, 8]]
    teensy: 1
  -
    nodes: [[9, 9]]
    teensy: 1
  -
    nodes: [[10, 10]]
    teensy: 2
  -
    nodes: [[11, 11]]
    teensy: 2
  -
    nodes: [[12, 12]]
    teensy: 2
  -
    nodes: [[13, 13]]
    teensy: 2
  -
    nodes: [[14, 14]]
    teensy: 2
  -
    nodes: [[15, 15]]
    teensy: 2
  -
    nodes: [[16, 16]]
    teensy: 2
  -
    nodes: [[17, 17]]
    teensy: 2
  -
    nodes: [[18, 18]]
    teensy: 2
  -
    nodes: [[19, 19]]
    teensy: 2
  -
    nodes: [[20, 20]]
    teensy: 3
  -
    nodes: [[21, 21]]
    teensy: 3
  -
    nodes: [[22, 22]]
    teensy: 3
  -
    nodes: [[23, 23]]
    teensy: 3
  -
    nodes: [[24, 24]]
    teensy: 3
  -
    nodes: [[25, 25]]
    teensy: 3
  -
    nodes: [[26, 26]]
    teensy: 3
  -
    nodes: [[27, 27]]
    teensy: 3
  -
    nodes: [[28, 28]]
    teensy: 3
  -
    nodes: [[29, 29]]
    teensy: 3
  -
    nodes: [[30, 30]]
    teensy: 4
  -
    nodes: [[31, 31]]
    teensy: 4
  -
    nodes: [[32, 32]]
    teensy: 4
  -
    nodes: [[33, 33]]
    teensy: 4
  -
    nodes: [[34, 34]]
    teensy: 4
  -
    nodes: [[35, 35]]
    teensy: 4
  -
    nodes: [[36, 36]]
    teensy: 4
  -
    nodes: [[37, 37]]
    teensy: 4
  -
    nodes: [[38, 38]]
    teensy: 4
  -
    nodes: [[39, 39]]
    teensy: 4


light_nodes: 
  -
    nodes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    num_leds: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
    num_leds_per_meter: 30
    teensy: 0
  -
    nodes: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
    num_leds: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
    num_leds_per_meter: 30
    teensy: 0
  -
    nodes: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
    num_leds_per_meter: 30
    num_leds: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
    teensy: 0
  -
    nodes: [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]
    num_leds: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
    num_leds_per_meter: 30
    teensy: 0


# Size of the nodes and color
nodes_size:
  x: 0.1016
  y: 0.1016
  z: 0.1016
nodes_color: [0.8, 0.8, 0.8, 1.0] # r,g,b,a

# Size of the light nodes and color
block_nodes_size:
  x: 0.23
  y: 0.23
  z: 0.23
block_nodes_color: [0.6, 0.6, 0.6, 1.0] # r,g,b,a

# Size of the beams and color
beams_size:
  x: 0.0317
  y: 0.0317
# z: 1.4 
  z: 0.01 
beams_color: [0.9, 0.9, 0.9, 0.7] # r,g,b,a

# Size of the block light beams and color
block_beams_size:
  x: 0.12
  y: 0.12
  z: 0.9 
block_beams_color: [0.8, 0.4, 0.4, 1.0] # r,g,b,a

# Size of the pixel light beams and color
pixel_beams_size:
  x: 0.12
  y: 0.12
  z: 0.9
pixel_beams_color: [0.8, 0.4, 0.4, 1.0] # r,g,b,a

# Size of the sensors and color
sensors_size:
  x: 0.045
  y: 0.045
# z: 0.7
  z: 0.01
sensors_color: [0.8, 0.8, 0.9, 0.4] # r,g,b,a
avg_sensors_size:
#  x: 0.75
#  y: 0.75
#  z: 0.75
  x: 0.4
  y: 0.4
  z: 0.4
avg_sensors_color: [0.8, 0.8, 0.9, 0.25] # r,g,b,a

# panels: [10,11,13, 12,13,16, 13,14,17, 15,16,20, 17,18,22, 19,20,24, 20,21,25, 21,22,26, 22,23,27, 28,29,32, 29,30,33, 31,32,36,32,33,37, 33,34,38, 35,36,41, 36,37,42, 37,38,43, 38,39,44, 40,41,46, 41,42,47, 42,43,48, 43,44,49, 44,45,50, 46,47,51, 48,49,53, 49,50,54, 47,48,52]
panels_color: [0.9, 0.9, 0.9, 0.4] # r,g,b,a

