ColorProcessor2:
  type: "dec_light_shows/DecColorProcessor"
  
  color_levels:
    -      
      start: 0.0
      color: [1.0, 1.0, 0.0, 1.0] # RGBA
    -
      start: 0.5
      color: [1.0, 0.0, 0.0, 0.5] # RGBA
    -
      start: 1.0
      color: [1.0, 0.0, 0.0, 0.75] # RGBA
