ColorBlackWhiteProcessor:
  type: "dec_light_shows/DecColorProcessor"
  
  color_levels:
    -      
      start: 0.0
      color: [1.0, 1.0, 1.0, 1.0] # RGBA
    -      
      start: 0.25
      color: [0.6, 0.6, 0.6, 0.75] # RGBA
    -      
      start: 0.5
      color: [0.0, 0.0, 0.0, 0.0] # RGBA
    -
      start: 0.65
      color: [0.8, 0.8, 0.1, 0.6] # RGBA
    -
      start: 1.0
      color: [1.0, 0.0, 0.0, 1.0] # RGBA
      