LightShowPlaneCreator:
  type: "dec_light_shows/DecLightShowPlaneCreator"
  visualization_rate: 1 # every n-th frame
  min_color: [1.0, 0.0, 0.0, 0.6]
  max_color: [1.0, 0.0, 0.0, 0.4]
  min_distance: 0.7
  max_distance: 1.4
  initial_normal: [0.0, 0.0, 1.0]
  initial_position: [0.0, 0.0, 3.0]
  initial_linear_velocity: [0.0, 0.0, 2.5]
 # initial_angular_velocity: [0.05, 0.0, 0.0]
  initial_angular_velocity: [0.0, 0.0, 0.0]
  initial_linear_acceleration: [0.0, 0.0, 0.0]
  initial_angular_acceleration: [0.0, 0.0, 0.0]
  virtual_cube_color: [0.0, 0.5, 0.5, 0.25]