OpenLoopBallRandom:
  type: "dec_light_shows/DecLightShowBallCreator"
  visualization_rate: 1 # every n-th frame
  min_color: [1.0, 0.0, 0.0, 0.6]
  max_color: [1.0, 0.0, 0.0, 0.4]
  min_distance: 0.7
  max_distance: 1.4
  initial_position: [0.0, 0.0, 0.77]
  initial_velocity: [0.2, 0.5, -0.4]
  initial_acceleration: [0.6, 1.5, 2.4]  
  virtual_cube_color: [0.0, 0.5, 0.5, 0.25]
  min_expansion_radius: 0.2
  max_expansion_radius: 2.5
  expansion_speed: 1.0 # in m/s
  profile_type: 0