SensorButterworth:
  type: "dec_light_shows/DecSensorButterworthProcessor"
  sensor_filter:
    name: Filter
    type: TransferFunctionFilter<float>
    params:
      a: [1.0000,   -0.5095]
      b: [0.7548,   -0.7548]