# Switches between simulation and real communication mode
simulation_mode: true

interaction_mode: 1
# LOCAL_ONLY = 1

# Number of arduinos in the structure
# Note: due to RS485 limitations we are limited to at most 30 (actually 32).
number_of_arduinos: 2
# Maximum number of sensors that can be hooked
# up with each arduino
max_number_of_sensors_per_arduino: 5
# Maximum number of lights that can be hooked
# up with each arduino
max_number_of_light_strips_per_arduino: 6
# Maximum number of leds that can be controlled by each arduino
max_number_of_leds_per_light_strip: 24

generate_configuration_file: true
generate_structure_file: true