# Switches between simulation and real communication mode
simulation_mode: true

interaction_mode: 1
# LOCAL_ONLY = 1

# Number of arduinos in the structure
# Note: due to RS485 limitations we are limited to at most 30 (actually 32).
number_of_arduinos: 4
# Maximum number of sensors that can be hooked
# up with each arduino
max_number_of_sensors_per_arduino: 5
# Maximum number of lights that can be hooked
# up with each arduino
max_number_of_lights_per_arduino: 6

