# List of all nodes in the structure
# Values correspond to x,y,z in meters
node_positions:
  - position: [0.0, 0.0, 0.0]
  - position: [1.0, 0.0, 0.0]
  - position: [1.0, 1.0, 0.0]
  - position: [0.0, 1.0, 0.0]
  - position: [0.0, 0.0, 1.0]
  - position: [1.0, 0.0, 1.0]
  - position: [1.0, 1.0, 1.0]
  - position: [0.0, 1.0, 1.0]
  - position: [2.0, 1.0, 1.0]

# List of all beams in the structure
# List correspond to pairs of indices of nodes
# nodes: [0, 1] constructs a beam from node 0 to node 1
beams:
  - nodes: [0, 1]
  - nodes: [1, 2]
  - nodes: [1, 3]
  - nodes: [2, 3]
  - nodes: [3, 0]
  - nodes: [4, 5]
  - nodes: [4, 6]
  - nodes: [5, 6]
  - nodes: [6, 7]
  - nodes: [7, 0]
  - nodes: [0, 4]
  - nodes: [1, 5]
  - nodes: [2, 6]
  - nodes: [3, 7]
  - nodes: [5, 7]
  - nodes: [5, 8]
  - nodes: [6, 8]
  - nodes: [4, 7]

# Which beams are sensors
# nodes: [0, 1] constructs a sensor from node 0 to node 1
sensors:
  - nodes: [0, 1]
  - nodes: [1, 2]
  - nodes: [4, 6]
  - nodes: [1, 3]
  - nodes: [4, 7]

# Which beams have light strips
# nodes: [0, 1] constructs a light strip from node 0 to node 1
light_beams:
  - nodes: [2, 6]
  - nodes: [3, 7]
  - nodes: [4, 5]
  - nodes: [5, 6]
  - nodes: [6, 7]

# Which nodes have light strips wrapped around
# [0, 2, 5] corresponds to light nodes at node 0, 2, and 5
light_nodes: [0, 5, 6]

# This list contains the arduino id to which this 
# light node is hooked up
# [2, 1, 2] means
# light node 0 is hooked up with arduino 2
# light node 1 is hooked up with arduino 1
# light node 2 is hooked up with arduino 2
# Note: Each node light must be hooked up to exactly
# one arduino. Thus, number of light_node_connections
# must equal the number of light_nodes specified.
light_node_connections: [0, 0, 0]
# This list contains the arduino id to which this 
# light beam is hooked up
# [2, 1, 2] means
# light beam 0 is hooked up with arduino 2
# light beam 1 is hooked up with arduino 1
# light beam 2 is hooked up with arduino 2
# Note: Each beam light must be hooked up to exactly
# one arduino. Thus, number of light_beam_connections
# must equal the number of light_beams specified.
light_beam_connections: [0, 0, 1, 2, 2]
# This list contains the arduino id to which this 
# sensor is hooked up
# [2, 1, 2] means
# sensor 0 is hooked up with arduino 2
# sensor 1 is hooked up with arduino 1
# sensor 2 is hooked up with arduino 2
# Note: Each sensor must be hooked up to exactly
# one arduino. Thus, number of sensor_connections
# must equal the number of sensors specified.
sensor_connections: [0, 0, 1, 2, 2]

# Size of the nodes and color
nodes_size:
  x: 0.07
  y: 0.07
  z: 0.07
nodes_color: [0.8, 0.8, 0.8, 1.0] # r,g,b,a

# Size of the light nodes and color
light_nodes_size:
  x: 0.1
  y: 0.1
  z: 0.1
light_nodes_color: [0.9, 0.9, 0.9, 1.0] # r,g,b,a

# Size of the beams and color
beams_size:
  x: 0.03
  y: 0.03
  z: 1.0
beams_color: [0.4, 0.4, 0.4, 1.0] # r,g,b,a

# Size of the light beams and color
light_beams_size:
  x: 0.08
  y: 0.08
  z: 0.8
light_beams_color: [0.8, 0.4, 0.4, 1.0] # r,g,b,a

# Size of the sensors and color
sensors_size:
  x: 0.04
  y: 0.04
  z: 0.9
sensors_color: [0.2, 0.2, 0.9, 0.9] # r,g,b,a

