point_cloud_topic: /camera2/depth_registered/points
light_frame_topic: light_frame2

# x, y, z, roll, pitch, yaw (in meters and degrees)
kinect_to_base_transform: [0.0, 0.0, -1.0, -40.0, 0.0, 0.0]

# x, y, z, roll, pitch, yaw (in meters and degrees)
base_to_sensor_area_transform: [0.0, -2.0, 1.3, 0.0, 0.0, 0.0]