point_cloud_topic: /camera1/depth/points

# x, y, z, roll, pitch, yaw (in meters and degrees)
# kinect_to_base_transform: [0.0, 0.0, -1.0, -40.0, 0.0, 0.0]
kinect_to_base_transform: [0.018421, -0.606554, 2.795792, -0.281540, 0.959550, 0.000000, -0.000000]

# x, y, z, roll, pitch, yaw (in meters and degrees)
base_to_sensor_area_transform: [0.2, 0.2, 1.3, 0.0, 0.0, 0.0]